import Head from "next/head";
import Image from "next/image";
import { MicrophoneIcon, ViewGridIcon, UserIcon, GlobeIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import { useRef } from "react";
import { useRouter } from "next/dist/client/router";
import { useTheme } from "next-themes";
export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  const {theme, setTheme} = useTheme();

  const changeTheme = () => {
    setTheme(theme === "dark" ? "light" : "dark");

  };
  if (theme === "dark") {
    window.onload = function() {
      document.getElementById("toggle").checked = true;
      }
  }

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;

    router.push(`/search?term=${term}`);
  };

  return (
    <div className={`${theme}`}>
      <div className="dark:bg-gray-800 flex flex-col items-center justify-center h-screen">
        <Head>
          <title>Google</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/*Header */}
        <header className="flex w-full p-5 justify-between text-sm text-gray-700 dark:text-gray-200">
          {/* Left */}
          <div className="flex space-x-4 items-center">
            <p className="link">About</p>
            <p className="link">Store</p>
          </div>

          {/* right */}
          <div className="flex space-x-4 items-center">
            <div className="flex justify-end items-center space-x-2">
              <span>Light</span>
            <input type="checkbox" id="toggle" className="hidden" />
            <label onClick={changeTheme} htmlFor="toggle">
              <div className="w-9 h-5 flex items-center rounded-full bg-gray-300 p-1">
              <div className="Toggle-dot w-4 h-4 rounded-full cursor-pointer bg-white shadow-md transition" ></div>
              </div>
            </label>
            <span>Dark</span>
            </div>

            <p className="link">Gmail</p>
            <p className="link">Images</p>

            {/*Icon*/}
            <ViewGridIcon className="dark:text-white w-10 h10 p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-900" />

            {/*Avatar*/}

              <UserIcon
              loading="lazy"
              className="h-8 rounded-full cursor-pointer transition duration-150 transform hover:scale-110"
            />
                
          </div>
        </header>
        {/* Body */}
        <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
          <Image
            src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
            alt="Google"
            height="100"
            width="300"
          />
          <div
            className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 dark:border-gray-900 dark:hover:border-gray-200
         px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl"
          >
            <SearchIcon className="dark:text-gray-200 h-5 mr-3 text-gray-500" />

            <input
              ref={searchInputRef}
              type="text"
              className="dark:bg-gray-800 dark:text-white flex-grow focus:outline-none"
            />
            <MicrophoneIcon className="dark:text-gray-200 h-5" />
          </div>
          <div
            className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 
        sm:flex-row sm:space-x-4"
          >
            <button onClick={search} className="hover:ring-1 dark:bg-gray-700 dark:text-white bg-gray-100 p-3 rounded-md ring-gray-200 text-sm text-gray-800
     focus:outline-none active:ring-gray-300 hover:shadow-md">
              Google Search
            </button>

            <button onClick={search} className="hover:ring-1 dark:bg-gray-700 dark:text-white bg-gray-100 p-3 rounded-md ring-gray-200 text-sm text-gray-800
     focus:outline-none active:ring-gray-300 hover:shadow-md ">I&apos;m Feeling Lucky</button>
          </div>
        </form>

        {/*Footer*/}
        <footer className="dark:bg-gray-800 grid w-full divide-y-[1px] divide-gray-300 dark:divide-gray-900 bg-gray-100 text-sm text-gray-500">
      <div className="px-8 py-3">
        <p>India</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-y-4 grid-flow-row-dense">
        <div className="flex justify-center items-center md:col-span-2 lg:col-span-1 lg:col-start-2">
          <GlobeIcon className="h-5 mr-1 text-green-700" />Carbon neutral since 2007
        </div>
      <div className="flex justify-center space-x-8 whitespace-nowrap md:justify-self-start">
        <p className="lg:p-4">Advertising</p>
        <p className="lg:p-4">Business</p>
        <p className="lg:p-4">How Search Works</p>
      </div>
      <div className="flex justify-center space-x-8 md:ml-auto">
          <p className="lg:p-4">Privacy</p>
          <p className="lg:p-4">Terms</p>
          <p className="lg:p-4">Settings</p>
      </div>
      </div>
    </footer>
      </div>
    </div>
  );
}
